### ISSUE TITLE
Team SGU

### ISSUE THREAD

**Issue by officialankan** [gwmodeling/challenge#25]
Geological Survey of Sweden

Model: SGU-HYPE
Names:  Anders Retzner

The model is based on the HYPE model (http://www.smhi.net/hype/wiki/doku.php?id=start) but with some added processes to improve groundwater level predictions.

**Comment by raoulcollenteur** [comment]
Hi @officialankan ! Just checking in if you are still planning to submit your results to the challenge? Late submission are allowed until 5th of January 24:00 CET. 

We would be happy to receive your results and have an additional model in the challenge :)

Cheers,

Raoul

**Comment by officialankan** [comment]
> Hi @officialankan ! Just checking in if you are still planning to submit your results to the challenge? Late submission are allowed until 5th of January 24:00 CET.
> 
> We would be happy to receive your results and have an additional model in the challenge :)
> 
> Cheers,
> 
> Raoul

woops! will finish this off hopefully yesterday then

**Comment by officialankan** [comment]
Sorry @raoulcollenteur, just couldn't come up with the time for this right now. Will keep the fork and hopefully still do it sometime this month.
